n_mlp_layers: 2
mlp_hidden_dims: 40
mlp_use_bn: True
mlp_activation: 'relu'

n_phi_layers: 8
hidden_phi_layers: 120
pe_dims: 4
node_emb_dims: 128

# Whether or not we use the 8 eigenvectors corresponding to the 8 smallest eigenvalues
smallest: False 
pe_type: 'signnet'